### ISSUE TITLE
Guadagno rx

### ISSUE THREAD

**Issue by gabri94** [AndreFre/TestJsonDispositivi#1]
Credo che le antenne dove è specificato solamente un generico "gain", questo si riferisca sia alla recezione che alla trasmissione.
Inserirei quindi lo stesso valore in entrambi i campi per semplificare il processamento dei dati.

https://github.com/AndreFre/TestJsonDisopositivi/blob/3b694449950aa74a9939898cd3d42147e1c45c70/Dispositivi/AM-NanoStation5AC.json#L8

**Comment by AndreFre** [comment]
aggiungo i valori su tutti i campi "gain_rx"
